2023-07-18 16:42:19,663 INFO    MainThread:4085 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2023-07-18 16:42:19,663 INFO    MainThread:4085 [wandb_setup.py:_flush():76] Configure stats pid to 4085
2023-07-18 16:42:19,663 INFO    MainThread:4085 [wandb_setup.py:_flush():76] Loading settings from /Users/heroofwisdom/.config/wandb/settings
2023-07-18 16:42:19,663 INFO    MainThread:4085 [wandb_setup.py:_flush():76] Loading settings from /Users/heroofwisdom/Documents/GitHub/Citrine_Test_V3/wandb/settings
2023-07-18 16:42:19,663 INFO    MainThread:4085 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-18 16:42:19,663 INFO    MainThread:4085 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-07-18 16:42:19,664 INFO    MainThread:4085 [wandb_init.py:_log_setup():507] Logging user logs to /Users/heroofwisdom/Documents/GitHub/Citrine_Test_V3/wandb/run-20230718_164219-uz5s4oqe/logs/debug.log
2023-07-18 16:42:19,664 INFO    MainThread:4085 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/heroofwisdom/Documents/GitHub/Citrine_Test_V3/wandb/run-20230718_164219-uz5s4oqe/logs/debug-internal.log
2023-07-18 16:42:19,665 INFO    MainThread:4085 [wandb_init.py:init():547] calling init triggers
2023-07-18 16:42:19,665 INFO    MainThread:4085 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-18 16:42:19,665 INFO    MainThread:4085 [wandb_init.py:init():596] starting backend
2023-07-18 16:42:19,665 INFO    MainThread:4085 [wandb_init.py:init():600] setting up manager
2023-07-18 16:42:19,667 INFO    MainThread:4085 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-07-18 16:42:19,668 INFO    MainThread:4085 [wandb_init.py:init():606] backend started and connected
2023-07-18 16:42:19,673 INFO    MainThread:4085 [wandb_run.py:_label_probe_notebook():1233] probe notebook
2023-07-18 16:42:19,674 INFO    MainThread:4085 [wandb_run.py:_label_probe_notebook():1243] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-07-18 16:42:19,674 INFO    MainThread:4085 [wandb_init.py:init():705] updated telemetry
2023-07-18 16:42:19,738 INFO    MainThread:4085 [wandb_init.py:init():738] communicating run to backend with 60.0 second timeout
2023-07-18 16:42:34,183 WARNING MainThread:4085 [wandb_init.py:init():1176] interrupted
Traceback (most recent call last):
  File "/Users/heroofwisdom/Documents/GitHub/Citrine_Test_V3/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
  File "/Users/heroofwisdom/Documents/GitHub/Citrine_Test_V3/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 741, in init
    result = run_init_handle.wait(
  File "/Users/heroofwisdom/Documents/GitHub/Citrine_Test_V3/.venv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/heroofwisdom/Documents/GitHub/Citrine_Test_V3/.venv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/heroofwisdom/Documents/GitHub/Citrine_Test_V3/.venv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-07-18 16:42:34,539 INFO    MainThread:4085 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-07-18 16:42:34,540 INFO    MainThread:4085 [wandb_init.py:_pause_backend():418] pausing backend
2023-07-18 16:42:38,029 INFO    MainThread:4085 [wandb_init.py:_resume_backend():423] resuming backend
2023-07-18 16:42:38,030 INFO    MainThread:4085 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-07-18 16:42:38,030 INFO    MainThread:4085 [wandb_init.py:_pause_backend():418] pausing backend
2023-07-18 16:42:41,651 INFO    MainThread:4085 [wandb_init.py:_resume_backend():423] resuming backend
2023-07-18 16:42:41,674 INFO    MainThread:4085 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2023-07-18 16:42:41,675 INFO    MainThread:4085 [wandb_setup.py:_flush():76] Configure stats pid to 4085
2023-07-18 16:42:41,675 INFO    MainThread:4085 [wandb_setup.py:_flush():76] Loading settings from /Users/heroofwisdom/.config/wandb/settings
2023-07-18 16:42:41,675 INFO    MainThread:4085 [wandb_setup.py:_flush():76] Loading settings from /Users/heroofwisdom/Documents/GitHub/Citrine_Test_V3/wandb/settings
2023-07-18 16:42:41,675 INFO    MainThread:4085 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-07-18 16:42:41,675 INFO    MainThread:4085 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-07-18 16:42:41,675 INFO    MainThread:4085 [wandb_init.py:_log_setup():507] Logging user logs to /Users/heroofwisdom/Documents/GitHub/Citrine_Test_V3/wandb/run-20230718_164241-uz5s4oqe/logs/debug.log
2023-07-18 16:42:41,675 INFO    MainThread:4085 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/heroofwisdom/Documents/GitHub/Citrine_Test_V3/wandb/run-20230718_164241-uz5s4oqe/logs/debug-internal.log
2023-07-18 16:42:41,675 INFO    MainThread:4085 [wandb_init.py:init():547] calling init triggers
2023-07-18 16:42:41,676 INFO    MainThread:4085 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-07-18 16:42:41,676 INFO    MainThread:4085 [wandb_init.py:init():596] starting backend
2023-07-18 16:42:41,676 INFO    MainThread:4085 [wandb_init.py:init():600] setting up manager
2023-07-18 16:42:41,677 INFO    MainThread:4085 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-07-18 16:42:41,678 INFO    MainThread:4085 [wandb_init.py:init():606] backend started and connected
2023-07-18 16:42:41,683 INFO    MainThread:4085 [wandb_run.py:_label_probe_notebook():1233] probe notebook
2023-07-18 16:42:41,683 INFO    MainThread:4085 [wandb_run.py:_label_probe_notebook():1243] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-07-18 16:42:41,684 INFO    MainThread:4085 [wandb_init.py:init():705] updated telemetry
2023-07-18 16:42:41,720 INFO    MainThread:4085 [wandb_init.py:init():738] communicating run to backend with 60.0 second timeout
2023-07-18 16:43:27,688 WARNING MainThread:4085 [wandb_init.py:init():1176] interrupted
Traceback (most recent call last):
  File "/Users/heroofwisdom/Documents/GitHub/Citrine_Test_V3/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1154, in init
    run = wi.init()
  File "/Users/heroofwisdom/Documents/GitHub/Citrine_Test_V3/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 741, in init
    result = run_init_handle.wait(
  File "/Users/heroofwisdom/Documents/GitHub/Citrine_Test_V3/.venv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/heroofwisdom/Documents/GitHub/Citrine_Test_V3/.venv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/heroofwisdom/Documents/GitHub/Citrine_Test_V3/.venv/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-07-18 16:43:27,816 INFO    MainThread:4085 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-07-18 16:43:27,817 INFO    MainThread:4085 [wandb_init.py:_pause_backend():418] pausing backend
